- alias: Master Bedroom Lights
  trigger:
    platform: state
    entity_id: binary_sensor.felipeishome
    from: "off"
    to: "on"
  action:
    service: switch.turn_on
    entity_id: switch.his_bedside_table
