homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1624
  unit_system: imperial
  time_zone: America/Denver
  customize: !include customize.yaml

# Front-end options
frontend:
#introduction:
config:
discovery:
history:
logbook:
map:
http:
  #api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  #base_url: example.duckdns.org:8123

sun:
updater:

ifttt:
  key: !secret ifttt_key

media_player:
  - platform: ps4
    host: 172.16.1.167

sensor:
  - platform: darksky
    api_key: !secret darksky_key
    monitored_conditions:
        - icon
        - nearest_storm_distance
  
  - platform: speedtest
    monitored_conditions:
        - download
        - upload

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
