kind: Namespace
apiVersion: v1
metadata:
  name: homebridge
  labels:
    name: homebridge
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-hb
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubernetes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-storage
  namespace: homebridge
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homebridge
  name: homebridge
  namespace: homebridge
spec:
  selector:
    matchLabels:
      app: homebridge
  replicas: 1
  template:
    metadata:
      labels:
        app: homebridge
        tier: frontend
    spec:
      volumes:
         - name: hb-storage
           persistentVolumeClaim:
            claimName: homebridge-storage
      containers:
      - name: homebridge
        image: oznu/homebridge:latest
        ports:
          - containerPort: 8581
        env:
        - name: TZ
          value: "America/Denver"
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: HOMEBRIDGE_CONFIG_UI
          value: "1"
        - name: HOMEBRIDGE_CONFIG_UI_PORT
          value: "8581"
        volumeMounts:
          - mountPath: "/homebridge"
            name: hb-storage
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: homebridge
spec:
  type: LoadBalancer
  selector:
    app: homebridge
    tier: frontend
  ports:
    - port: 8581
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebridge
  namespace: homebridge
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-replacement: "^http://192.168.1.43:8581"
spec:
  rules:
  - http:
      paths:
      - path: /homebridge
        pathType: Prefix
        backend:
          service:
            name: homebridge
            port:
              number: 8581