kind: Namespace
apiVersion: v1
metadata:
  name: homebridge
  labels:
    name: homebridge
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: homebridge-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/cluster/kube-data/homebridge
    server: 192.168.1.2
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-vc
  namespace: homebridge
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homebridge
  name: homebridge
  namespace: homebridge
spec:
  selector:
    matchLabels:
      app: homebridge
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homebridge
        tier: frontend
    spec:
      hostNetwork: true
      containers:
        - name: homebridge
          image: oznu/homebridge
          ports:
            - containerPort: 8581
            - containerPort: 51416
          env:
            - name: TZ
              value: "America/Denver"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: HOMEBRIDGE_CONFIG_UI
              value: "1"
            - name: HOMEBRIDGE_CONFIG_UI_PORT
              value: "8581"
          volumeMounts:
            - name: homebridge-vc
              mountPath: /homebridge
      volumes:
        - name: homebridge-vc
          persistentVolumeClaim:
            claimName: homebridge-vc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: homebridge
spec:
  selector:
    app: homebridge
    tier: frontend
  ports:
    - protocol: TCP
      port: 8581
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge-service
  namespace: homebridge
spec:
  selector:
    app: homebridge
    tier: frontend
  ports:
    - protocol: TCP
      port: 51416
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: homebridge
#   namespace: homebridge
#   annotations:
#     kubernetes.io/ingress.class: "traefik"
#     # traefik.ingress.kubernetes.io/redirect-replacement: "^http://192.168.1.2:8581"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /homebridge
#         pathType: Prefix
#         backend:
#           service:
#             name: homebridge
#             port:
#               number: 8581
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: homebridge
#   namespace: homebridge
#   labels:
#     app: homebridge
# spec:
#   type: ClusterIP
#   selector:
#     app: homebridge
#     tier: frontend
#   ports:
#   - protocol: TCP
#     port: 8581
